#AVR_TOOLS_DIR=/usr/

# See http://www.mjoldfield.com/atelier/2009/02/arduino-cli.html
MCU = atmega328p
AVRDUDE_ARD_BAUDRATE = 19200
F_CPU = 8000000
ISP_PORT = /dev/ttyACM0
ISP_PROG = avrisp

ARDUINO_LIBS =
ARDMK_DIR = ../arduino-makefile

include ${ARDMK_DIR}/Arduino.mk
